name: GraviDupeControl
version: '${version}'
main: org.unfr.graviDupeControl.GraviDupeControl
api-version: '1.21'
authors: [ Unfr ]
description: Allows to control which gravity blocks are allowed to be duped through end portal
commands:
  gdcr:
    description: Reload GraviDupeControl configuration.
    usage: /<command>
    permission: gravidupecontrol.reload
    permission-message: You do not have permission to use this command.
